---
policies:
  - type: commit
    spec:
      header:
        length: 200
        imperative: true
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - ci
          - Merge branch
          - Revert
        scopes:
          - .*
        descriptionLength: 100
