---
policies:
  - type: commit
    spec:
      header:
        length: 200
        imperative: true
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - refactor
          - perf
          - chore
          - test
          - docs
          - Merge branch
          - Revert
        scopes:
          - release
          - deps
          - ci
          - container
        descriptionLength: 100
